<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Lipun" failures="1" tests="2" name="Default test(failed)(failed)" time="0.095" errors="0" timestamp="2023-12-12T00:22:10 IST">
  <testcase classname="general.RetryFailedTests" name="test2" time="0.021">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at general.RetryFailedTests.test2(RetryFailedTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="general.RetryFailedTests" name="test4" time="0.004"/>
  <testcase classname="general.RetryFailedTests" name="test5" time="0.0">
    <ignored/>
  </testcase> <!-- test5 -->
  <testcase classname="general.RetryFailedTests" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="general.RetryFailedTests" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
